// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBarzaNeCyahLHXe5iYtibJn1S8q_U1gck',
    appId: '1:872517935357:web:1be3843f5b7590a75cde94',
    messagingSenderId: '872517935357',
    projectId: 'money-warden',
    authDomain: 'money-warden.firebaseapp.com',
    storageBucket: 'money-warden.appspot.com',
    measurementId: 'G-WCCKLBRNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhpNzU1eASwkrr0ehbcKKeuDunV0ISio',
    appId: '1:872517935357:android:272a11ec6a2c75335cde94',
    messagingSenderId: '872517935357',
    projectId: 'money-warden',
    storageBucket: 'money-warden.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DRCkRERGgiGajXAn37ZHikd4X6j6-n4',
    appId: '1:872517935357:ios:d2aa9479cc16b3925cde94',
    messagingSenderId: '872517935357',
    projectId: 'money-warden',
    storageBucket: 'money-warden.appspot.com',
    androidClientId: '872517935357-nh6sagjt0b49sjrbals4plo8tkeb8ec8.apps.googleusercontent.com',
    iosClientId: '872517935357-9qppganjl5kf73o4l5doinpnbdo3unpk.apps.googleusercontent.com',
    iosBundleId: 'in.hrus.moneywarden.moneyWarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DRCkRERGgiGajXAn37ZHikd4X6j6-n4',
    appId: '1:872517935357:ios:d2aa9479cc16b3925cde94',
    messagingSenderId: '872517935357',
    projectId: 'money-warden',
    storageBucket: 'money-warden.appspot.com',
    androidClientId: '872517935357-nh6sagjt0b49sjrbals4plo8tkeb8ec8.apps.googleusercontent.com',
    iosClientId: '872517935357-9qppganjl5kf73o4l5doinpnbdo3unpk.apps.googleusercontent.com',
    iosBundleId: 'in.hrus.moneywarden.moneyWarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBarzaNeCyahLHXe5iYtibJn1S8q_U1gck',
    appId: '1:872517935357:web:f434fca71bd33e4c5cde94',
    messagingSenderId: '872517935357',
    projectId: 'money-warden',
    authDomain: 'money-warden.firebaseapp.com',
    storageBucket: 'money-warden.appspot.com',
    measurementId: 'G-6HMY0ZMZ0W',
  );

}